# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.linspace(0, 5, 11)
# to receive an array of 10 evenly spaced points between 0 and 5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(4)
# identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.51765775, 0.25656472, 0.81920492, 0.55550001, 0.67510616])

In [18]:
np.random.rand(5,5)
# uniform distribution of random numbers

array([[0.76470064, 0.97950339, 0.91121637, 0.91558492, 0.17313206],
       [0.55309799, 0.00331605, 0.30697673, 0.47199613, 0.03781018],
       [0.20848874, 0.94955255, 0.5090471 , 0.85158893, 0.22463478],
       [0.31710983, 0.05797593, 0.94694447, 0.73908896, 0.81207684],
       [0.91793558, 0.59363967, 0.66947511, 0.3617633 , 0.28884501]])

In [19]:
np.random.randn(2)
# gaussian distribution of random numbers

array([-0.17587343,  0.25008618])

In [20]:
np.random.randn(4,4)

array([[-0.49417842,  0.03101003, -0.22660874, -0.24550529],
       [ 0.79703666, -0.37048561,  1.05331598,  1.18903467],
       [ 0.22461584, -0.27854225,  0.41825234, -0.90384617],
       [ 1.2051362 , -0.0197989 , -0.5933711 ,  0.8951293 ]])

In [22]:
np.random.randint(1,100)
# gives random integer between 1 and 100 (not including 100)

93

In [24]:
np.random.randint(1,100,10)
# gives 10 random numbers

array([63,  4, 95, 13, 52,  3, 31,  3, 26, 40])

In [45]:
arr = np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([31, 30, 28, 30, 48, 46, 18, 32, 29, 23])

In [32]:
arr.reshape(5,5) 
# NB: will get error if the array does not fill up the new array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()
# returns the max value in ranarr

48

In [34]:
ranarr.min()

18

In [37]:
ranarr.argmax()
# returns index location number of the max value in ranarr

4

In [36]:
ranarr.argmin()

6

In [47]:
arr.shape
# Gives the shape of the array (the below is a one dimensional
# as it only has one figure

(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr.shape

(5, 5)

In [51]:
arr.dtype
# Shows data type that its in an array.

dtype('int64')

In [52]:
from numpy.random import randint

In [53]:
randint(2,10)

3