In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing in arrays works very similarly to indexing lists in Python

In [5]:
arr[4]

4

In [6]:
arr[4:6]

array([4, 5])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

### Numpy arrays differ from lists in Python because you can broadcast

In [10]:
arr[0:5] = 100

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr2 = np.arange(0,11)

In [17]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr2 = arr2[0:6]

In [19]:
slice_of_arr2

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr2[:] = 99

In [21]:
slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [22]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### Note how by broadcasting '99' to the slice has also changed the original array. This is how Numpy helps with memory of very large arrays.

#### i.e. if you make changes to an equated variable of an original array - it will change the original array too.

#### However if you want to make a copy of an array to edit you can do the following.

In [28]:
arr2_copy = arr2.copy()

In [29]:
(arr2) == (arr2_copy)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [32]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr2_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
# If we do a change...
arr2_copy[:] = 100

In [35]:
arr2_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [36]:
# but note - arr2 hasn't changed!
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr2 == arr2_copy

array([False, False, False, False, False, False, False, False, False,
       False, False])

### Indexing a 2D Array

In [38]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [39]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

#### There are two general formats for grabbing elements from a 2D array or matrix:
        - Double bracket format
        - Single bracket format with a comma (favoured)

##### For a single element

In [41]:
# Double bracket format
print(arr_2d[0])
print(arr_2d[0][0])
print(arr_2d[2][1])

[ 5 10 15]
5
40


In [44]:
arr_2d[0][0]

5

In [40]:
# Single bracket format
arr_2d[1,2]

30

##### For > single element

In [39]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

##### For conditional selection

In [47]:
arr3 = np.arange(1,11)

In [48]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
bool_arr3 = arr3 > 5

In [51]:
bool_arr3 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [52]:
# We can use the created boolean array to conditionally select the 
# elements of the original array that meet the condition.
arr3[bool_arr3]

array([ 6,  7,  8,  9, 10])

In [54]:
# We can do much of the above on one line:
arr3[arr3>5]

array([ 6,  7,  8,  9, 10])

In [62]:
arr3[arr3<3]

array([1, 2])

###### A couple of examples

In [56]:
arr2_2d = np.arange(50).reshape(5,10)

In [57]:
arr2_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arr2_2d[1:4,2:8]

array([[12, 13, 14, 15, 16, 17],
       [22, 23, 24, 25, 26, 27],
       [32, 33, 34, 35, 36, 37]])

In [60]:
arr2_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])